version: '3'
services:
  broker1:
    container_name: broker1
    hostname: broker1
    image: wurstmeister/kafka
    privileged: true
    restart: unless-stopped
    ports:
      - "9986:9986"
      - "9091:9091"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://:9091
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.16.12.163:9091
      KAFKA_ADVERTISED_HOST_NAME: 172.16.12.163
      KAFKA_ADVERTISED_PORT: 9091
      KAFKA_ZOOKEEPER_CONNECT: 172.16.12.130:2181,172.16.12.130:2182,172.16.12.130:2183
      JMX_PORT: 9986
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/kafka/broker1:/kafka/kafka-logs-broker2
    networks:
      default:
        ipv4_address: 172.19.0.11


  broker2:
    container_name: broker2
    hostname: broker2
    image: wurstmeister/kafka
    privileged: true
    restart: unless-stopped
    ports:
      - "9987:9987"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.16.12.163:9092
      KAFKA_ADVERTISED_HOST_NAME: 172.16.12.163
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: 172.16.12.130:2181,172.16.12.130:2182,172.16.12.130:2183
      JMX_PORT: 9987
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/kafka/broker2:/kafka/kafka-logs-broker2
    networks:
      default:
        ipv4_address: 172.19.0.12


  broker3:
    container_name: broker3
    hostname: broker3
    image: wurstmeister/kafka
    privileged: true
    restart: unless-stopped
    ports:
      - "9988:9988"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_LISTENERS: PLAINTEXT://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.16.12.163:9093
      KAFKA_ADVERTISED_HOST_NAME: 172.16.12.163
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: 172.16.12.130:2181,172.16.12.130:2182,172.16.12.130:2183
      JMX_PORT: 9988
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /data/kafka/broker3:/kafka/kafk-logs-broker3
    networks:
      default:
        ipv4_address: 172.19.0.13



  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    container_name: kafka-manager
    hostname: kafka-manager
    restart: unless-stopped
    ports:
      - 9000:9000
    links:      # 连接本compose文件创建的container
      - broker1
      - broker2
      - broker3

    environment:
      ZK_HOSTS: 172.16.12.130:2181,172.16.12.130:2182,172.16.12.130:2183
      KAFKA_BROKERS: broker1:9091,broker2:9092,broker3:9093
      APPLICATION_SECRET: 123456
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    networks:
      default:
        ipv4_address: 172.19.0.14

networks:
  default:
    external:
      name: kafka_net